/*
 * Copyright (c) 2020 Devtron Labs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

update config_map_env_level set secret_data = '{"secrets":[{"name":"cred","type":"environment","external":true,"data":nil,"global":false,"externalType":"AWSSecretsManager","secretData":[{"key":"aws_s3/secureSecret","name":"AWS.S3.CREDENTIALS.SECRETKEY","isBinary":false},{"key":"sendmoney/db-user","name":"SPRING_DATASOURCE_USERNAME","isBinary":false},{"key":"sendmoney/db-user","name":"SPRING_REPORTING_DATASOURCE_USERNAME","isBinary":false},{"key":"sendmoney/db-pass","name":"SPRING_DATASOURCE_PASSWORD","isBinary":false},{"key":"sendmoney/db-pass","name":"SPRING_REPORTING_DATASOURCE_PASSWORD","isBinary":false},{"key":"aws_s3/secure_accessKey","name":"AWS.S3.CREDENTIALS.ACCESSKEY","isBinary":false}],"roleARN":""}]}' where id=8 and updated_on <= '2020-07-02 15:00:00';
update config_map_env_level set secret_data = '{"secrets":[{"name":"api-gateway-sec","type":"environment","external":true,"data":nil,"global":false,"externalType":"AWSSecretsManager","secretData":[{"key":"sendmoney/db-user","name":"SPRING_DATASOURCE_USERNAME","isBinary":false},{"key":"sendmoney/db-user","name":"SPRING_REPORTING_DATASOURCE_USERNAME","isBinary":false},{"key":"sendmoney/db-pass","name":"SPRING_DATASOURCE_PASSWORD","isBinary":false},{"key":"sendmoney/db-pass","name":"SPRING_REPORTING_DATASOURCE_PASSWORD","isBinary":false},{"key":"aws_s3/secure_accessKey","name":"AWS.S3.CREDENTIALS.ACCESSKEY","isBinary":false},{"key":"aws_s3/secureSecret","name":"AWS.S3.CREDENTIALS.SECRETKEY","isBinary":false}],"roleARN":""}]}' where id=51 and updated_on <= '2020-07-02 15:00:00';
update config_map_env_level set secret_data = '{"secrets":null}' where id=1 and updated_on <= '2020-07-02 15:00:00';
update config_map_env_level set secret_data = '{"secrets":[{"name":"deposit-scheduler-config","type":"environment","external":true,"data":null,"global":false,"externalType":"AWSSecretsManager","secretData":[{"key":"aws_s3/accessKey","name":"AWS.S3.CREDENTIALS.ACCESSKEY","isBinary":false},{"key":"aws_s3/secretKey","name":"AWS.S3.CREDENTIALS.SECRETKEY","isBinary":false},{"key":"sendmoney/db-pass","name":"SPRING.DATASOURCE.PASSWORD","isBinary":false},{"key":"sendmoney/db-user","name":"SPRING.DATASOURCE.USERNAME","isBinary":false},{"key":"gupshup_whatsapp/user","name":"WHATSAPP.GUPSHUP.USERID","isBinary":false},{"key":"gupshup_whatsapp/password","name":"WHATSAPP.GUPSHUP.PASSWORD","isBinary":false}],"roleARN":""}]}' where id=52 and updated_on <= '2020-07-02 15:00:00';
update config_map_env_level set secret_data = '{"secrets":[{"name":"ext-sec-t","type":"volume","external":true,"mountPath":"/etc/extsec-t/","data":null,"global":false,"externalType":"AWSSecretsManager","secretData":[{"key":"hello-service/password","name":"password.properties","isBinary":false}],,"roleARN":""}]}' where id=16 and updated_on <= '2020-07-02 15:00:00';
update config_map_env_level set secret_data = '{"secrets":[{"name":"dbcred","type":"environment","external":true,"data":null,"global":false,"externalType":"AWSSecretsManager","secretData":[{"key":"sendmoney/db-user","name":"SPRING_DATASOURCE_USERNAME","isBinary":false},{"key":"sendmoney/db-pass","name":"SPRING_DATASOURCE_PASSWORD","isBinary":false}],"roleARN":""}]}' where id=14 and updated_on <= '2020-07-02 15:00:00';
update config_map_env_level set secret_data = '{"secrets":[{"name":"ext-sec-t","type":"environment","external":true,"data":null,"global":false,"externalType":"AWSSecretsManager","secretData":[{"key":"hello-service/password","name":"password_properties","isBinary":false}],"roleARN":""}]}' where id=19 and updated_on <= '2020-07-02 15:00:00';
update config_map_env_level set secret_data = '{"secrets":[{"name":"db","type":"environment","external":true,"data":null,"global":false,"externalType":"AWSSecretsManager","secretData":[{"key":"sendmoney/db-user","name":"SPRING_DATASOURCE_USERNAME","isBinary":false},{"key":"sendmoney/db-pass","name":"SPRING_DATASOURCE_PASSWORD","isBinary":false}],"roleARN":""}]}' where id=21 and updated_on <= '2020-07-02 15:00:00';
update config_map_env_level set secret_data = '{"secrets":[{"name":"cred","type":"environment","external":true,"data":null,"global":false,"externalType":"AWSSecretsManager","secretData":[{"key":"merchant_otp/password","name":"OTP_MYSQL_PASSWORD","isBinary":false},{"key":"merchant_otp/user","name":"OTP_MYSQL_USER","isBinary":false}],"roleARN":""}]}' where id=26 and updated_on <= '2020-07-02 15:00:00';
update config_map_env_level set secret_data = '{"secrets":[{"name":"cred","type":"environment","external":true,"data":null,"global":false,"externalType":"AWSSecretsManager","secretData":[{"key":"merchant_otp/password","name":"OTP_MYSQL_PASSWORD","isBinary":false},{"key":"merchant_otp/user","name":"OTP_MYSQL_USER","isBinary":false}],"roleARN":""}]}' where id=28 and updated_on <= '2020-07-02 15:00:00';
update config_map_env_level set secret_data = '{"secrets":[{"name":"db-cred","type":"environment","external":true,"data":null,"global":false,"externalType":"AWSSecretsManager","secretData":[{"key":"aws_s3/secretKey","name":"AWS.S3.CREDENTIALS.SECRETKEY","isBinary":false},{"key":"sendmoney/db-user","name":"SPRING_DATASOURCE_USERNAME","isBinary":false},{"key":"sendmoney/db-pass","name":"SPRING_DATASOURCE_PASSWORD","isBinary":false},{"key":"gupshup_whatsapp/user","name":"WHATSAPP.GUPSHUP.USERID","isBinary":false},{"key":"gupshup_whatsapp/password","name":"WHATSAPP.GUPSHUP.PASSWORD","isBinary":false},{"key":"aws_s3/accessKey","name":"AWS.S3.CREDENTIALS.ACCESSKEY","isBinary":false}],"roleARN":""}]}' where id=9 and updated_on <= '2020-07-02 15:00:00';
update config_map_env_level set secret_data = '{"secrets":[{"name":"database","type":"environment","external":true,"data":null,"global":false,"externalType":"AWSSecretsManager","secretData":[{"key":"sendmoney/db-pass","name":"SPRING_DATASOURCE_PASSWORD","isBinary":false},{"key":"gupshup_whatsapp/user","name":"WHATSAPP.GUPSHUP.USERID","isBinary":false},{"key":"gupshup_whatsapp/password","name":"WHATSAPP.GUPSHUP.PASSWORD","isBinary":false},{"key":"aws_s3/accessKey","name":"AWS.S3.CREDENTIALS.ACCESSKEY","isBinary":false},{"key":"aws_s3/secretKey","name":"AWS.S3.CREDENTIALS.SECRETKEY","isBinary":false},{"key":"sendmoney/db-user","name":"SPRING_DATASOURCE_USERNAME","isBinary":false}],"roleARN":""}]}' where id=20 and updated_on <= '2020-07-02 15:00:00';
update config_map_env_level set secret_data = '{"secrets":[{"name":"recharge-cred-prod","type":"environment","external":true,"data":null,"global":false,"externalType":"AWSSecretsManager","secretData":[{"key":"sendmoney/db-user","name":"SPRING.DATASOURCE.USERNAME","isBinary":false},{"key":"sendmoney/db-pass","name":"SPRING.DATASOURCE.PASSWORD","isBinary":false},{"key":"aws_s3/accessKey","name":"AWS.S3.CREDENTIALS.ACCESSKEY","isBinary":false},{"key":"aws_s3/secretKey","name":"AWS.S3.CREDENTIALS.SECRETKEY","isBinary":false},{"key":"send-grid/user_id","name":"SENDGRID.MAIL.USERID","isBinary":false},{"key":"send-grid/password","name":"SENDGRID.MAIL.PASSWORD","isBinary":false}],"roleARN":""}]}' where id=29 and updated_on <= '2020-07-02 15:00:00';
update config_map_env_level set secret_data = '{"secrets":[{"name":"recharge-scheduler-cred","type":"environment","external":true,"data":null,"global":false,"externalType":"AWSSecretsManager","secretData":[{"key":"aws_s3/secretKey","name":"AWS.S3.CREDENTIALS.SECRETKEY","isBinary":false},{"key":"send-grid/user_id","name":"SENDGRID.MAIL.USERID","isBinary":false},{"key":"send-grid/password","name":"SENDGRID.MAIL.PASSWORD","isBinary":false},{"key":"sendmoney/db-user","name":"SPRING.DATASOURCE.USERNAME","isBinary":false},{"key":"sendmoney/db-pass","name":"SPRING.DATASOURCE.PASSWORD","isBinary":false},{"key":"aws_s3/accessKey","name":"AWS.S3.CREDENTIALS.ACCESSKEY","isBinary":false}],"roleARN":""}]}' where id=41 and updated_on <= '2020-07-02 15:00:00';
update config_map_env_level set secret_data = '{"secrets":[{"name":"api-gateway-sec","type":"environment","external":true,"data":null,"global":false,"externalType":"AWSSecretsManager","secretData":[{"key":"sendmoney/db-user","name":"SPRING_REPORTING_DATASOURCE_USERNAME","isBinary":false},{"key":"sendmoney/db-pass","name":"SPRING_DATASOURCE_PASSWORD","isBinary":false},{"key":"sendmoney/db-pass","name":"SPRING_REPORTING_DATASOURCE_PASSWORD","isBinary":false},{"key":"aws_s3/secure_accessKey","name":"AWS.S3.CREDENTIALS.ACCESSKEY","isBinary":false},{"key":"aws_s3/secureSecret","name":"AWS.S3.CREDENTIALS.SECRETKEY","isBinary":false},{"key":"sendmoney/db-user","name":"SPRING_DATASOURCE_USERNAME","isBinary":false}],"roleARN":""}]}' where id=42 and updated_on <= '2020-07-02 15:00:00';
update config_map_env_level set secret_data = '{"secrets":[{"name":"cred","type":"environment","external":true,"data":null,"global":false,"externalType":"AWSSecretsManager","secretData":[{"key":"","name":"OTP_MYSQL_PASSWORD","isBinary":false},{"key":"","name":"OTP_MYSQL_USER","isBinary":false}],"roleARN":""}]}' where id=49 and updated_on <= '2020-07-02 15:00:00';
