apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: devtroncd-oss-2
spec:
  interval: 10m
  url: https://github.com/stefanprodan/podinfo
  ref:
    branch: master
