DROP SEQUENCE IF EXISTS "id_seq_k8s_resource_history_sequence";
DROP TABLE IF EXISTS "kubernetes_resource_history";


SELECT "cd_workflow_runner".*,
       "cd_workflow"."id" AS "cd_workflow__id",
       "cd_workflow"."pipeline_id" AS "cd_workflow__pipeline_id",
       "cd_workflow__pipeline"."id" AS "cd_workflow__pipeline__id",
       "cd_workflow__pipeline"."deployment_app_name" AS "cd_workflow__pipeline__deployment_app_name",
       "cd_workflow__pipeline"."deleted" AS "cd_workflow__pipeline__deleted",
       "cd_workflow__pipeline__environment"."id" AS "cd_workflow__pipeline__environment__id",
       "cd_workflow__pipeline__environment"."environment_name" AS "cd_workflow__pipeline__environment__environment_name",
       "cd_workflow__pipeline__environment"."cluster_id" AS "cd_workflow__pipeline__environment__cluster_id",
       "cd_workflow__pipeline__environment"."active" AS "cd_workflow__pipeline__environment__active",
       "cd_workflow__pipeline__environment"."default" AS "cd_workflow__pipeline__environment__default", "cd_workflow__pipeline__environment"."grafana_datasource_id" AS "cd_workflow__pipeline__environment__grafana_datasource_id", "cd_workflow__pipeline__environment"."namespace" AS "cd_workflow__pipeline__environment__namespace", "cd_workflow__pipeline__environment"."environment_identifier" AS "cd_workflow__pipeline__environment__environment_identifier", "cd_workflow__pipeline__environment"."description" AS "cd_workflow__pipeline__environment__description", "cd_workflow__pipeline__environment"."is_virtual_environment" AS "cd_workflow__pipeline__environment__is_virtual_environment", "cd_workflow__pipeline__environment"."created_on" AS "cd_workflow__pipeline__environment__created_on", "cd_workflow__pipeline__environment"."created_by" AS "cd_workflow__pipeline__environment__created_by", "cd_workflow__pipeline__environment"."updated_on" AS "cd_workflow__pipeline__environment__updated_on", "cd_workflow__pipeline__environment"."updated_by" AS "cd_workflow__pipeline__environment__updated_by" FROM cd_workflow_runner AS "cd_workflow_runner" LEFT JOIN cd_workflow AS "cd_workflow" ON "cd_workflow"."id" = "cd_workflow_runner"."cd_workflow_id" LEFT JOIN pipeline AS "cd_workflow__pipeline" ON "cd_workflow__pipeline"."id" = "cd_workflow"."pipeline_id" LEFT JOIN environment AS "cd_workflow__pipeline__environment" ON "cd_workflow__pipeline__environment"."id" = "cd_workflow__pipeline"."environment_id" INNER JOIN cd_workflow wf on wf.id = cd_workflow_runner.cd_workflow_id INNER JOIN pipeline p on p.id = wf.pipeline_id INNER JOIN environment e on e.id = p.environment_id LEFT JOIN deployment_config dc on dc.app_id = p.app_id and dc.environment_id=p.environment_id WHERE (cd_workflow_runner.workflow_type='DEPLOY') AND (cd_workflow_runner.status not in ('Aborted','Failed','Succeeded','HIBERNATING','Healthy','Degraded','Initiating','Queued','Starting')) AND (cd_workflow_runner.cd_workflow_id in (SELECT max(cd_workflow.id) as id from cd_workflow INNER JOIN cd_workflow_runner on cd_workflow.id = cd_workflow_runner.cd_workflow_id WHERE cd_workflow_runner.status != 'Queued' GROUP BY cd_workflow.pipeline_id ORDER BY cd_workflow.pipeline_id desc)) AND ((p.deployment_app_type='helm' or dc.deployment_app_type='helm')) AND (cd_workflow_runner.started_on > NOW() - INTERVAL '12 hours') AND (p.deleted=FALSE) ORDER BY "cd_workflow_runner"."id" DESC