DELETE FROM plugin_step_variable WHERE name = 'CodacyEndpoint'
DELETE FROM plugin_step_variable WHERE name = 'GitProvider'
DELETE FROM plugin_step_variable WHERE name = 'CodacyApiToken'
DELETE FROM plugin_step_variable WHERE name = 'Organisation'
DELETE FROM plugin_step_variable WHERE name = 'RepoName'
DELETE FROM plugin_step_variable WHERE name = 'Branch'
DELETE FROM plugin_step_variable WHERE name = 'NUMBER_OF_ISSUES'