DROP INDEX "public"."environment_id_idx";
DROP INDEX "public"."app_id_idx";
DROP INDEX "public"."app_name_idx";
DROP INDEX "public"."ci_artifact_id_idx";
DROP INDEX "public"."cdwf_pipeline_id_idx";
DROP INDEX "public"."cdwf_workflow_status_idx";
DROP INDEX "public"."pco_pipeline_id_idx";
DROP INDEX "public"."pco_deployment_type_idx";
DROP INDEX "public"."cdwfr_cd_workflow_id_idx";