update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-gke-provisioner.png' where name='GKE Provisioner v1.1.0';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-email-notifier.png' where name='Custom Email Notifier v1.0.0';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-notify-webhook.png' where name='Custom Webhook Notifier v1.0.0';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-pull-image-from-registry.png' where name='Pull images from container repository';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-copy-container-image.png' where name='Copy container image';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-hadolint.png' where name='Docker Lint';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-k6-load-testing.png' where name='';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-sonarqube.png' where name='Sonarqube';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-dtrack.png' where name='Dependency track for Python';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-dtrack.png' where name='Dependency track for NodeJs';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-dtrack.png' where name='Dependency track for Maven & Gradle';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-semgrep.png' where name='Semgrep';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-codacy.png' where name='Codacy';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-jira-updater.png' where name='Jira Issue Validator';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-jira-updater.png' where name='Jira Issue Updater';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-github-pr-updater.png' where name='Github Pull Request Updater';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-trigger-jenkins.png' where name='Jenkins';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-security-scan.png' where name='Vulnerability Scanning';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-terraform-cli.png' where name='Terraform CLI v1.0.0';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-ansible.png' where name='Ansible Runner v1.0.0';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-sonarqube.png' where name='Sonarqube v1.1.0';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-cloudanix-imagescan.png' where name='Cloudanix Imagescan v1.0.0';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-gcs-bucket.png' where name='GCS Create Bucket';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-dockerslim.png' where name='DockerSlim v1.0.0';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-eks-cluster.png' where name='EKS Create Cluster v1.0.0';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-copacetic.png' where name='Copacetic v1.0.0';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-container-image-exporter.png' where name='Container Image Exporter v1.0.0';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-github-release.png' where name='Github Release Plugin v1.0';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-cosign.png' where name='Cosign v1.0.0';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-github-branch-divergence-checker.png' where name='GitHub Branch Divergence Checker v1.0';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-apply-k8s-job.png' where name='Apply JOB in k8s v1.0.0';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-github-pr-closer.png' where name='Github Pull Request Closer v1.0';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-mail-master.png' where name='Mail Master v1.0.0';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-devtron-ci-trigger.png' where name='Devtron CI Trigger v1.0.0';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-devtron-cd-trigger.png' where name='Devtron CD Trigger v1.0.0';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-devtron-job-trigger.png' where name='Devtron Job Trigger v1.0.0';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-security-scan.png' where name='Vulnerabilty_Scanner v1.0.0';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-bitbucket-runner-trigger.png' where name='BitBucket Runner Trigger v1.0.0';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-golang-migrate.png' where name='GoLang-migrate';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-crane.png' where name='CraneCopy';
update plugin_parent_metadata set icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-devtron-ci-trigger.png' where name='Devtron CI Trigger';

