UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-poll-container-registry.png' WHERE name='Pull images from container repository';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/ic-plugin-copy-container-image.png' WHERE name='Copy container image';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/hadolint.png' WHERE name='Docker Lint';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/k6-plugin-icon.png' WHERE name='K6 Load testing';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/sonarqube-plugin-icon.png' WHERE name='Sonarqube';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/dTrack-plugin-icon.png' WHERE name='Dependency track for Python';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/dTrack-plugin-icon.png' WHERE name='Dependency track for NodeJs';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/dTrack-plugin-icon.png' WHERE name='Dependency track for Maven & Gradle';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/semgrep.png' WHERE name='Semgrep';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/codacy-plugin-icon.png' WHERE name='Codacy';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-jira.png' WHERE name='Jira Issue Validator';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-jira.png' WHERE name='Jira Issue Updater';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-github-pr.png' WHERE name='Github Pull Request Updater';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/jenkins.png' WHERE name='Jenkins';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/ic-plugin-vulnerability-scan.png' WHERE name='Vulnerability Scanning';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/terraform-cli.svg' WHERE name='Terraform CLI v1.0.0';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/ansible-runner.svg' WHERE name='Ansible Runner v1.0.0';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/sonarqube-plugin-icon.png' WHERE name='Sonarqube v1.1.0';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/cloudanix-logo.png' WHERE name='Cloudanix Imagescan v1.0.0';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/ajaydevtron/devtron/main/assets/gke-plugin-icon.png' WHERE name='GKE Provisioner v1.1.0';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/gcs-bucket.svg' WHERE name='GCS Create Bucket';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/dockerslim-plugin-icon.png' WHERE name='DockerSlim v1.0.0';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/eks-plugin-icon.svg' WHERE name='EKS Create Cluster v1.0.0';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/copa-plugin-icon.png' WHERE name='Copacetic v1.0.0';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/docker-logo.png' WHERE name='Container Image Exporter v1.0.0';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/GithubReleasePluginlogo.png' WHERE name='Github Release Plugin v1.0';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/cosign-logo.png' WHERE name='Cosign v1.0.0';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/branch-compare-plugin-logo.png' WHERE name='GitHub Branch Divergence Checker v1.0';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/devtron-logo-plugin.png' WHERE name='Apply JOB in k8s v1.0.0';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/GithubPullRequest-Plugin-logo.png' WHERE name='Github Pull Request Closer v1.0';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/MailMaster.png' WHERE name='Mail Master v1.0.0';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/devtron-logo-plugin.png' WHERE name='Devtron CI Trigger v1.0.0';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/devtron-logo-plugin.png' WHERE name='Devtron CD Trigger v1.0.0';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/devtron-logo-plugin.png' WHERE name='Devtron Job Trigger v1.0.0';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/devtron-logo-plugin.png' WHERE name='Vulnerabilty_Scanner v1.0.0';
UPDATE plugin_parent_metadata SET icon='https://t4.ftcdn.net/jpg/04/76/40/09/240_F_476400965_iYkCpMeqvQwaICySZBgyP5IErlyAgeZu.jpg' WHERE name='Custom Email Notifier v1.0.0';
UPDATE plugin_parent_metadata SET icon='https://seeklogo.com/images/W/webhooks-logo-04229CC4AE-seeklogo.com.png' WHERE name='Custom Webhook Notifier v1.0.0';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/bitbucket-logo-plugin.jpeg' WHERE name='BitBucket Runner Trigger v1.0.0';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-golang-migrate.png' WHERE name='GoLang-migrate';
UPDATE plugin_parent_metadata SET icon='https://raw.githubusercontent.com/devtron-labs/devtron/main/assets/plugin-icons/ic-plugin-crane.png' WHERE name='CraneCopy';
update plugin_parent_metadata set icon='' where name='Devtron CI Trigger';
