{{- if $.Values.autoscaling.enabled }}
{{- if semverCompare ">=1.23-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: autoscaling/v2
{{- else if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: autoscaling/v2beta2
{{- else }}
apiVersion: autoscaling/v2beta1
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  {{- if $.Values.autoscaling.name }}
  name: {{ $.Values.autoscaling.name }}
  {{- else }}
  name: {{ template ".Chart.Name .fullname" $ }}-hpa
  {{- end }}
  {{- if .Values.autoscaling.annotations }}
  annotations:
{{ toYaml .Values.autoscaling.annotations | indent 4 }}
  {{- end }}
  labels:
    appId: {{ $.Values.app | quote }}
    envId: {{ $.Values.env | quote }}
    app: {{ template ".Chart.Name .name" $ }}
    chart: {{ template ".Chart.Name .chart" $ }}
    release: {{ $.Release.Name }}  
  {{- if .Values.autoscaling.labels }}
{{ toYaml .Values.autoscaling.labels | indent 4 }}
  {{- end }}
{{- if $.Values.appLabels }}
{{ toYaml $.Values.appLabels | indent 4 }}
{{- end }}  
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include ".Chart.Name .fullname" $ }}
  minReplicas: {{ $.Values.autoscaling.MinReplicas  }}
  maxReplicas: {{ $.Values.autoscaling.MaxReplicas }}
  metrics:
  {{- if  $.Values.autoscaling.containerResource.enabled  }}
  {{- with $.Values.autoscaling.containerResource }}
  {{- if .TargetCPUUtilizationPercentage }}
  - type: ContainerResource  
    containerResource:
      name: cpu
      container: {{ $.Chart.Name }}
      target:
        type: Utilization
        averageUtilization: {{ .TargetCPUUtilizationPercentage }}
  {{- end}}  
  {{- if .TargetMemoryUtilizationPercentage  }}
  - type: ContainerResource  
    containerResource:
      name: memory
      container: {{ $.Chart.Name }}
      target:
        type: Utilization
        averageUtilization: {{ .TargetMemoryUtilizationPercentage }}
  {{- end}}
  {{- end }}            
  {{- end }}  
  {{- if $.Values.autoscaling.TargetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      {{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion }}
      target:
        type: Utilization
        averageUtilization: {{ $.Values.autoscaling.TargetMemoryUtilizationPercentage }}
      {{- else }}
      targetAverageUtilization: {{ $.Values.autoscaling.TargetMemoryUtilizationPercentage }}
      {{- end }}
  {{- end }}
  {{- if $.Values.autoscaling.TargetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      {{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion }}
      target:
        type: Utilization
        averageUtilization: {{ $.Values.autoscaling.TargetCPUUtilizationPercentage }}
      {{- else }}
      targetAverageUtilization: {{ $.Values.autoscaling.TargetCPUUtilizationPercentage }}
      {{- end }}
  {{- end }}
    {{- if and $.Values.autoscaling.extraMetrics (semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion) }}
  {{- toYaml $.Values.autoscaling.extraMetrics | nindent 2 }}
    {{- end}}
  {{- if and $.Values.autoscaling.behavior (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  behavior:
    {{- toYaml $.Values.autoscaling.behavior | nindent 4 }}
  {{- end }}
  {{- end }}
{{- $primaryAutoscaling := $.Values.autoscaling | default dict }}
{{- $secAutoscaling := $.Values.secondaryWorkload.autoscaling | default dict }}
{{- $secHpaEnabled := false }}
{{- if $.Values.secondaryWorkload.enabled }}
  {{- if hasKey $secAutoscaling "enabled" }}
    {{- $secHpaEnabled = $secAutoscaling.enabled }}
  {{- else }}
    {{- $secHpaEnabled = $primaryAutoscaling.enabled }}
  {{- end }}
{{- end }}
{{- if $secHpaEnabled }}
---
{{- if semverCompare ">=1.23-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: autoscaling/v2
{{- else if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: autoscaling/v2beta2
{{- else }}
apiVersion: autoscaling/v2beta1
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  {{- if and $secAutoscaling $secAutoscaling.name }}
  name: {{ $secAutoscaling.name }}
  {{- else }}
  name: {{ template ".Chart.Name .fullname" $ }}-{{ $.Values.secondaryWorkload.postfix | default "sec" }}-hpa
  {{- end }}
  {{- if and $secAutoscaling $secAutoscaling.annotations }}
  annotations:
{{ toYaml $secAutoscaling.annotations | indent 4 }}
  {{- else if $primaryAutoscaling.annotations }}
  annotations:
{{ toYaml $primaryAutoscaling.annotations | indent 4 }}
  {{- end }}
  labels:
    appId: {{ $.Values.app | quote }}
    envId: {{ $.Values.env | quote }}
    app: {{ template ".Chart.Name .name" $ }}
    chart: {{ template ".Chart.Name .chart" $ }}
    release: {{ $.Release.Name }}
  {{- if and $secAutoscaling $secAutoscaling.labels }}
{{ toYaml $secAutoscaling.labels | indent 4 }}
  {{- else if $primaryAutoscaling.labels }}
{{ toYaml $primaryAutoscaling.labels | indent 4 }}
  {{- end }}
{{- if $.Values.appLabels }}
{{ toYaml $.Values.appLabels | indent 4 }}
{{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include ".Chart.Name .fullname" $ }}-{{ $.Values.secondaryWorkload.postfix | default "sec" }}
  minReplicas: {{ $secAutoscaling.MinReplicas | default $primaryAutoscaling.MinReplicas | default 1 }}
  maxReplicas: {{ $secAutoscaling.MaxReplicas | default $primaryAutoscaling.MaxReplicas | default 2 }}
  metrics:
  {{- $containerResource := $secAutoscaling.containerResource | default $primaryAutoscaling.containerResource | default dict }}
  {{- if $containerResource.enabled }}
  {{- if $containerResource.TargetCPUUtilizationPercentage }}
  - type: ContainerResource
    containerResource:
      name: cpu
      container: "{{ if $.Values.secondaryWorkload.containerName }}{{ $.Values.secondaryWorkload.containerName }}{{ else if $.Values.containerName }}{{ $.Values.containerName }}{{ else }}{{ $.Chart.Name }}{{ end }}"
      target:
        type: Utilization
        averageUtilization: {{ $containerResource.TargetCPUUtilizationPercentage }}
  {{- end }}
  {{- if $containerResource.TargetMemoryUtilizationPercentage }}
  - type: ContainerResource
    containerResource:
      name: memory
      container: "{{ if $.Values.secondaryWorkload.containerName }}{{ $.Values.secondaryWorkload.containerName }}{{ else if $.Values.containerName }}{{ $.Values.containerName }}{{ else }}{{ $.Chart.Name }}{{ end }}"
      target:
        type: Utilization
        averageUtilization: {{ $containerResource.TargetMemoryUtilizationPercentage }}
  {{- end }}
  {{- end }}
  {{- $targetMemory := "" }}
  {{- if hasKey $secAutoscaling "TargetMemoryUtilizationPercentage" }}
    {{- $targetMemory = $secAutoscaling.TargetMemoryUtilizationPercentage }}
  {{- else if hasKey $primaryAutoscaling "TargetMemoryUtilizationPercentage" }}
    {{- $targetMemory = $primaryAutoscaling.TargetMemoryUtilizationPercentage }}
  {{- end }}
  {{- if $targetMemory }}
  - type: Resource
    resource:
      name: memory
      {{- if semverCompare ">=1.16-0" $.Capabilities.KubeVersion.GitVersion }}
      target:
        type: Utilization
        averageUtilization: {{ $targetMemory }}
      {{- else }}
      targetAverageUtilization: {{ $targetMemory }}
      {{- end }}
  {{- end }}
  {{- $targetCPU := "" }}
  {{- if hasKey $secAutoscaling "TargetCPUUtilizationPercentage" }}
    {{- $targetCPU = $secAutoscaling.TargetCPUUtilizationPercentage }}
  {{- else if hasKey $primaryAutoscaling "TargetCPUUtilizationPercentage" }}
    {{- $targetCPU = $primaryAutoscaling.TargetCPUUtilizationPercentage }}
  {{- end }}
  {{- if $targetCPU }}
  - type: Resource
    resource:
      name: cpu
      {{- if semverCompare ">=1.16-0" $.Capabilities.KubeVersion.GitVersion }}
      target:
        type: Utilization
        averageUtilization: {{ $targetCPU }}
      {{- else }}
      targetAverageUtilization: {{ $targetCPU }}
      {{- end }}
  {{- end }}
  {{- $extraMetrics := $secAutoscaling.extraMetrics | default $primaryAutoscaling.extraMetrics }}
  {{- if and $extraMetrics (semverCompare ">=1.16-0" $.Capabilities.KubeVersion.GitVersion) }}
  {{- toYaml $extraMetrics | nindent 2 }}
  {{- end }}
  {{- $behavior := $secAutoscaling.behavior | default $primaryAutoscaling.behavior }}
  {{- if and $behavior (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
  behavior:
    {{- toYaml $behavior | nindent 4 }}
  {{- end }}
{{- end }}
