// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	chartRepoRepository "github.com/devtron-labs/devtron/pkg/chartRepo/repository"
	commonService "github.com/devtron-labs/devtron/pkg/commonService"

	mock "github.com/stretchr/testify/mock"
)

// CommonService is an autogenerated mock type for the CommonService type
type CommonService struct {
	mock.Mock
}

// EnvironmentVariableList provides a mock function with given fields:
func (_m *CommonService) EnvironmentVariableList() (*commonService.EnvironmentVariableList, error) {
	ret := _m.Called()

	var r0 *commonService.EnvironmentVariableList
	var r1 error
	if rf, ok := ret.Get(0).(func() (*commonService.EnvironmentVariableList, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *commonService.EnvironmentVariableList); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonService.EnvironmentVariableList)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchLatestChart provides a mock function with given fields: appId, envId
func (_m *CommonService) FetchLatestChart(appId int, envId int) (*chartRepoRepository.Chart, error) {
	ret := _m.Called(appId, envId)

	var r0 *chartRepoRepository.Chart
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (*chartRepoRepository.Chart, error)); ok {
		return rf(appId, envId)
	}
	if rf, ok := ret.Get(0).(func(int, int) *chartRepoRepository.Chart); ok {
		r0 = rf(appId, envId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chartRepoRepository.Chart)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(appId, envId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GlobalChecklist provides a mock function with given fields:
func (_m *CommonService) GlobalChecklist() (*commonService.GlobalChecklist, error) {
	ret := _m.Called()

	var r0 *commonService.GlobalChecklist
	var r1 error
	if rf, ok := ret.Get(0).(func() (*commonService.GlobalChecklist, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *commonService.GlobalChecklist); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonService.GlobalChecklist)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCommonService interface {
	mock.TestingT
	Cleanup(func())
}

// NewCommonService creates a new instance of CommonService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCommonService(t mockConstructorTestingTNewCommonService) *CommonService {
	mock := &CommonService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
